[package]
name = "rust-graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
getrandom = { version = "0.2", features = ["js"] }
miniquad = "0.4.6"

[profile.release]
lto = true
codegen-units = 1
strip = true
